DeepDive-Final-Project/frontend

- src/stores/useUserStore.ts
- typescript 에러 수정을 위한 pr 입니다.
> [Fix]: typescript error

- src/components/Location/InterestSelector.tsx
- src/components/Location/UserList.tsx
- src/components/Location/UserLocation.tsx
- src/pages/LocationPage.tsx
- src/stores/useUserStore.ts
> [Fix] : deploy error

- src/pages/LoginPage.tsx
- 이미지 태그 안에 잘못 넣은 onClick을 수정했습니다.
> [fix] 로그인 핸들러 수정

- src/pages/LocationPage.tsx
> [fix] vercel 배포 오류

- package-lock.json
- src/components/location/LocationButton.tsx
- src/components/location/LocationNavBar.tsx
- src/components/location/ProfileListTest.tsx
- src/components/location/UserLocation.tsx
- src/pages/LocationPage.tsx
배포된 사이트에서 데이터를 주고 받을 수 있는지 테스트용 입니다.
- 임의로 정해져있는 id와 위도 경도를 보냅니다.
- 주위 유저의 정보를  받아옵니다.
> [feat] 배포 서버에서의 통신 테스트

- src/App.tsx
- src/components/profile/Accordian.tsx
- src/components/profile/DropDown.tsx
- src/components/profile/InputField.tsx
- src/components/profile/LinkInput.tsx
- src/components/profile/Modal.tsx
- src/components/profile/ModalContent.tsx
- src/index.css
- src/pages/profile/ProfileInfoPage.tsx
- src/pages/profile/ProfileInterestPage.tsx
- src/pages/profile/ProfileJobPage.tsx
- src/pages/profile/ProfileLinkPage.tsx
> - closes #26 
프로필 정보 4번째 단계 페이지 입니다.
- 모바일, 태블릿, 데스크탑 사이즈 UI를 구현했습니다.
- 커스텀 스크롤바 디자인을 추가하였습니다.
- 모달, 아코디언 컴포넌트 분리하였습니다.
- 데이터 확인을 위한 콘솔 로그를 포함하였습니다.
- 디테일한 디자인은 수정될 예정입니다. (ex.아이템별 컬러값)
> [feat] 프로필 관심사 등록

- src/App.tsx
- src/pages/profile/ProfileIntroPage.tsx
> - closes #35 
프로필 정보 마지막 단계 페이지 입니다.
- 모바일, 태블릿, 데스크탑 사이즈 UI를 구현했습니다.
- 최대 200자 제한 및 현재 글자수를 확인할 수 있습니다.
- 현재 페이지에서 작성완료 버튼을 누를 경우, 앞선 유저의 정보를 한번에 전송합니다.
> [feat] 프로필 자기소개 등록

- src/pages/profile/ProfileImgPage.tsx
- src/pages/profile/ProfileInfoPage.tsx
- src/pages/profile/ProfileInterestPage.tsx
- src/pages/profile/ProfileIntroPage.tsx
- src/pages/profile/ProfileJobPage.tsx
- src/pages/profile/ProfileLinkPage.tsx
- src/stores/useProfileStore.ts
> - closes #37  
사용자의 데이터를 등록합니다.
- 사용자의 정보를 전역상태로 관리하고, 저장합니다.
- 임시 프로필 이미지 등록 기능을 추가했습니다.
- 임시 provider값을 지정했습니다.
- 프로필 이미지 크롭 기능이 추가될 예정입니다.
- 입력값 미입력시 버튼이 클릭되지 않도록 수정될 예정입니다.
- 상세 디자인 수정 예정입니다.
> [feat] 프로필 데이터 등록

- src/hooks/useChatRequestFetch.ts
- src/pages/TestPage.tsx
> - closes #45 
인증 기반 로그인 연동 에러를 해결합니다.
사용자가 채팅 테스트 페이지에 접속했을 때, 화면이 정상적으로 표시되지 않는 문제
- 로그인된 사용자의 정보를 안정적으로 가져오도록 방어 처리 코드를 추가했습니다.
이상 없다면 다시 진행하겠습니다..🥲
> [fix] localStorage 제거 및 인증 기반 채팅 연동 에러 해결

- src/components/location/Filter.tsx
> [fix] vercel 오류 해결

- src/components/location/LocationButton.tsx
> [fix] Authoization 정보만 받아오기

- src/components/location/LocationButton.tsx
> [fix] env가 잘 먹히는지 테스트

- src/components/location/LocationButton.tsx
> [fix] cookie 받기 수정

- src/components/location/LocationButton.tsx
> [fix] fix cookie 

- src/components/location/LocationButton.tsx
> [fix] edit cookie2

- src/components/location/LocationButton.tsx
> [fix] coookie

- src/components/location/LocationButton.tsx
> [fix] data 형식 수정

- src/components/location/LocationButton.tsx
> [fix] data 수정

- src/components/location/LocationButton.tsx
> [fix] data

- src/pages/profile/LoginPage.tsx
- src/pages/profile/ProfileInfoPage.tsx
> [feat] 로그인한 유저정보 데이터 테스트

- src/components/location/LocationButton.tsx
> [fix] env url 실수

- src/components/location/BottomSheet.tsx
- src/components/location/UserLocation.tsx
- src/stores/useUserStore.ts
> [feat] 유저 포커스 기능

- src/components/location/RightSheet.tsx
> [fix] rightsheet 에러 

- src/components/location/UserLocation.tsx
> [fix] Locaion edit

- src/components/location/UserLocation.tsx
> [fix] users 추가 입니다.

- src/components/location/BottomSheet.tsx
- src/components/location/UserCard.tsx
- src/hooks/useReceivedChatRequests.ts
> [feat] 버튼 기능 활성화

- src/App.tsx
- src/components/chatting/ChatBubble.tsx
- src/components/chatting/ChatHeader.tsx
- src/components/chatting/ChatList.tsx
- src/components/chatting/ChatListItem.tsx
- src/components/chatting/ChatSideBar.tsx
- src/components/common/ConfirmModal.tsx
- src/pages/ChatPage.tsx
>- closes #71 
채팅방 나가기 클릭 시 팝업 추가 및 자잘한 수정을 같이 진행했습니다.
- 확인용 임시 팝업 공통 컴포넌트 추가
- 채팅방 나가기 버튼 클릭 시 확인 팝업이 뜨도록 기능 추가
- 채팅 리스트에서 상대방 이름이 잘못 표시되는 문제 수정
- 채팅방 리스트 클릭 시 넓이가 늘어나는 문제 수정
- 토스트 알림 필요없는 속성 제거, 스타일 수정
- 팝업 관련 애니메이션은 추후에 진행하도록 하겠습니다.
> [feat] 채팅방 나가기 클릭 시 팝업 추가

- src/components/location/BottomSheet.tsx
- src/hooks/useReceivedChatRequests.ts
> [feat] message

- src/components/location/BottomSheet.tsx
- src/components/location/UserCard.tsx
> [feat] 메세지 기능 수정

- src/components/location/BottomSheet.tsx
> [fix] 바텀시트 수정

- src/components/location/LocationNavBar.tsx
- src/hooks/useLogout.ts
> [feat] 새로고침 버튼

- src/components/location/LocationButton.tsx
> [fix] 작동하지 않는 코드 삭제

- package-lock.json
- src/components/location/BottomSheet.tsx
- src/components/location/LocationNavBar.tsx
- src/pages/LocationPage.tsx
> [feat] 이미지 불러오기

- src/components/location/LocationNavBar.tsx
> [feat] image

- src/components/location/BottomSheet.tsx
- src/components/location/LocationNavBar.tsx
- src/components/location/UserCard.tsx
- src/stores/useUserStore.ts
> [fix] 대소문자 

- .gitignore
- src/components/location/LocationButton.tsx
> [fix] nickName

- src/components/location/LocationButton.tsx
> nickName fix

- src/pages/LocationPage.tsx
> [fix] delete button

- src/components/location/BottomSheet.tsx
- src/components/location/LocationNavBar.tsx
- src/components/location/UserCard.tsx
- src/components/location/UserLocation.tsx
- src/pages/LocationPage.tsx
버튼 스타일링을 수정하고 usercard에 있는 채팅방 이동하기 관련 버튼 기능 구현
> [feat] 버튼 스타일링 수정 및 기능 추가

- src/components/location/LocationNavBar.tsx
- src/components/location/UserCard.tsx
> [fix] css 스타일 수정

- src/components/location/UserCard.tsx
> [fix] 유저카드 반응형 수정

- src/components/chatting/ChatMessageItem.tsx
- src/components/common/ConfirmModal.tsx
- src/pages/ChatPage.tsx
- src/pages/ProfilePreviewPage.tsx
>- closes #106 
채팅 관련 페이지 자잘한 스타일 및 버그를 수정합니다.
- `/profilePreview` 페이지 
- 버튼 상태 실시간 반영 오류 수정
- `/chat` 페이지
- 반응형 수정
- 확인 팝업 여백 추가
> [fix] 채팅 관련 페이지 자잘한 스타일 및 버그 수정

- src/components/location/BottomSheet.tsx
> [feat] 버튼 실시간 조정

- src/components/location/BottomSheet.tsx
- src/components/location/Filter.tsx
- src/components/location/UserCard.tsx
> [design] 유저 카드 부분 세부 디자인 변경

- src/components/location/BottomSheet.tsx
- src/components/location/UserCard.tsx
> [design] usercard 디자인 수정입니다.

- src/components/location/BottomSheet.tsx
> [feat] 유저 카드 디자인 수정

- src/components/location/BottomSheet.tsx
> [feat] 버튼 기능 추가

- src/components/location/RightSheet.tsx
> [fix] rightsheet 수정

- src/components/location/BottomSheet.tsx
> [fix]: button

- src/components/location/BottomSheet.tsx
> fix: bolean

- src/components/location/BottomSheet.tsx
> [fix] button

- src/components/location/BottomSheet.tsx
> [feat] fix scroll

- src/components/location/BottomSheet.tsx
- src/components/location/UserLocation.tsx
> [feat] 버튼 누를 시 chat 보낸 요청에 띄우기

- src/components/location/BottomSheet.tsx
> [feat] chat area로 카드 이동

- src/components/location/UserCard.tsx
> [feat] chat 모드에서 버튼 활성화

- src/components/location/BottomSheet.tsx
- src/components/location/UserCard.tsx
- src/components/location/UserLocation.tsx
- src/pages/LocationPage.tsx
> [feat] 실시간 버튼 구현 

- src/components/location/BottomSheet.tsx
- src/pages/LocationPage.tsx
> [feat] 실시간 버튼 수정 2

- src/components/location/BottomSheet.tsx
- src/components/location/UserCard.tsx
> [fix] react.memo 삭제

- src/components/location/BottomSheet.tsx
> [feat] 실시간 버튼을 위한 요소 삭제

- src/components/location/BottomSheet.tsx
> [feat] 실시간 버튼 수정

- src/components/location/BottomSheet.tsx
> [fix] 스펠링 체크 

- src/components/location/LocationNavBar.tsx
- src/components/location/UserCard.tsx
- src/components/location/UserLocation.tsx
- 더보기 버튼을 세부적으로 나눠 버튼 색 구현
- 더보기 세팅 수정 화면 위로 나타남.
> [feat] 더보기 버튼 세부 변화 더보기 세팅 수정

- src/components/location/LocationNavBar.tsx
- src/components/location/UserLocation.tsx
- src/stores/useUserStore.ts
> [feat] 유저 이미지 배치

- src/components/location/LocationNavBar.tsx
- src/components/location/UserLocation.tsx
> [fix] 이미지 확인을 위한 콘솔 적용

- src/components/location/LocationNavBar.tsx
- src/components/location/UserLocation.tsx
- src/stores/useUserStore.ts
> [fix] 내 이미지 받아오는 api 경로 수정

- src/components/location/UserLocation.tsx
> [feat] 유저들 이미지 

- src/components/location/LocationNavBar.tsx
- src/components/location/UserLocation.tsx
> [design] 이미지 css 수정

- src/components/chatting/ChatListItem.tsx
- src/components/chatting/ChatRoom.tsx
- src/pages/ProfilePreviewPage.tsx
> - closes #127
채팅방 리스트 안 읽은 메시지 수 인디케이터 표시 테스트 코드입니다.
채팅방 리스트 안 읽은 메시지 수 인디케이터 표시 테스트
채팅 화면 관련 자잘한 수정 진행
안 읽은 메시지 수 적용 전, 테스트 코드입니다.
문제 발생시 추후에 수정하겠습니다!👍
> [feat] 채팅방 리스트 안 읽은 메시지 수 인디케이터 표시 테스트

- src/components/location/UserLocation.tsx
> [feat] 이미지 조정

- src/components/location/UserLocation.tsx
> [feat] 레이더 혼자 있을 때 뜨게 하기

- src/components/location/LocationNavBar.tsx
> [fix] api 요청 방식 수정

- src/components/location/UserLocation.tsx
> [feat] 강조부분

- src/components/location/BottomSheet.tsx
> [fix] z-index

- src/components/location/BottomSheet.tsx
- src/components/location/LocationNavBar.tsx
- src/components/location/UserLocation.tsx
- src/stores/useUserStore.ts
> [feat] 강조 부분 첫 번째로 이동

- src/assets/images/Group 6.svg
> [fea] 원 svg 파일 추가

- src/components/location/UserLocation.tsx
> [fix] 원 상태 변경

- src/components/location/UserLocation.tsx
> design: circle

- src/components/location/BottomSheet.tsx
> [feat] 알림기능 추가

- src/components/location/BottomSheet.tsx
> chore: console

- src/components/location/BottomSheet.tsx
> fix: realtime

- src/components/profile/ModalContent.tsx
> [design] update interests name
